# nixpacks.toml
[phases.setup]
nixPkgs = ["python311", "python311.pkgs.setuptools"]

[phases.install]
cmds = [
  "pip install --upgrade pip",
  "pip install setuptools wheel",
  "pip install -r requirements.txt"
]

[start]
cmd = "gunicorn --worker-class gevent --worker-connections 1000 -w 1 server2:app"
